#!/bin/bash          
# Jason Quisberth hw 8 cs507

# to use: ./sigsender some_PID 
# echo $1 will be the first cmd line argument to be the pid

for i in `seq 1 50`;
do
	if [ $i -ne 9 ]; 
	then
		kill -$i $1
	fi
done
