CFLAGS=-I
cc=gcc

dirLoc=/home/jason/Documents/CS507_UnixProgramming/drchipdbg
libloc=/home/jason/Documents/CS507_UnixProgramming/drchipdbg/xtdio.a
libhloc=/home/jason/Documents/CS507_UnixProgramming/drchipdbg/xtdio.h

all: 
	$(cc) $(CFLAGS) fcntlget.c $(libloc)


